from django.urls import path
from .views import (
    register_employee,
    login_employee,
    admin_login,
    send_otp,
    reset_password,
    send_registration_otp,
    verify_registration_otp,
    get_profile,
    update_profile,
    update_profile_photo,
    update_face,
    admin_employees,
    admin_update_employee,
    admin_reset_employee_password,
    chat_contacts,
    chat_history,
    chat_history_clear,
    chat_message_send,
    chat_message_detail,
    chat_message_react,
    list_groups,
    create_group,
    group_history,
    group_message_send,
    add_group_member,
    remove_group_member,
    delete_group,
    chat_unread_count,
    update_group,
    group_message_detail,
)

urlpatterns = [
    path("register/", register_employee, name="register"),
    path("login/", login_employee, name="login"),
    path("admin-login/", admin_login, name="admin-login"),
    path("send-otp/", send_otp, name="send-otp"),
    path("reset-password/", reset_password, name="reset-password"),
    path("send-registration-otp/", send_registration_otp, name="send_registration_otp"),
    path(
        "verify-registration-otp/",
        verify_registration_otp,
        name="verify-registration-otp",
    ),
    path("profile/", get_profile, name="profile"),
    path("update-profile/", update_profile, name="update-profile"),
    path("update-profile-photo/", update_profile_photo, name="update-profile-photo"),
    path("update-face/", update_face, name="update-face"),
    path("admin-employees/", admin_employees, name="admin-employees"),
    path("chat-contacts/", chat_contacts, name="chat-contacts"),
    path("chat-history/", chat_history, name="chat-history"),
    path("chat-history/clear/", chat_history_clear, name="chat-history-clear"),
    path("chat-message/send/", chat_message_send, name="chat-message-send"),
    path("chat-message/<str:message_id>/", chat_message_detail, name="chat-message"),
    path(
        "chat-message/<str:message_id>/react/",
        chat_message_react,
        name="chat-message-react",
    ),
    path("admin-update-employee/", admin_update_employee, name="admin-update-employee"),
    path(
        "admin-reset-password/",
        admin_reset_employee_password,
        name="admin-reset-password",
    ),
    path("chat-groups/", list_groups, name="chat-groups"),
    path("chat-groups/create/", create_group, name="chat-groups-create"),
    path("chat-groups/history/", group_history, name="chat-groups-history"),
    path("chat-groups/message/send/", group_message_send, name="chat-groups-send"),
    path("chat-unread-count/", chat_unread_count, name="chat-unread-count"),
    path(
        "chat-groups/message/<str:message_id>/",
        group_message_detail,
        name="chat-groups-message-detail",
    ),
    path("chat-groups/<str:group_id>/update/", update_group, name="chat-groups-update"),
    path("chat-groups/add-member/", add_group_member, name="chat-groups-add-member"),
    path(
        "chat-groups/remove-member/",
        remove_group_member,
        name="chat-groups-remove-member",
    ),
    path("chat-groups/<str:group_id>/", delete_group, name="chat-groups-delete"),
]
