from django.urls import path
from .views import (
    register_employee,
    login_employee,
    admin_login,
    send_otp,
    reset_password,
    send_registration_otp,
    verify_registration_otp,
    get_profile,
    update_profile,
    update_profile_photo,
    update_face,
    admin_employees,
    admin_update_employee,
    admin_reset_employee_password,
    chat_contacts,
    chat_history,
)

urlpatterns = [
    path("register/", register_employee, name="register"),
    path("login/", login_employee, name="login"),
    path("admin-login/", admin_login, name="admin-login"),
    path("send-otp/", send_otp, name="send-otp"),
    path("reset-password/", reset_password, name="reset-password"),
    path("send-registration-otp/", send_registration_otp, name="send_registration_otp"),
    path(
        "verify-registration-otp/",
        verify_registration_otp,
        name="verify-registration-otp",
    ),
    path("profile/", get_profile, name="profile"),
    path("update-profile/", update_profile, name="update-profile"),
    path("update-profile-photo/", update_profile_photo, name="update-profile-photo"),
    path("update-face/", update_face, name="update-face"),
    path("admin-employees/", admin_employees, name="admin-employees"),
    path("chat-contacts/", chat_contacts, name="chat-contacts"),
    path("chat-history/", chat_history, name="chat-history"),
    path("admin-update-employee/", admin_update_employee, name="admin-update-employee"),
    path(
        "admin-reset-password/",
        admin_reset_employee_password,
        name="admin-reset-password",
    ),
]
